controllers/ListsController.php
<?php

namespace app\controllers;


use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\data\Pagination;
use app\models\Lists;
class ListsController extends \yii\web\Controller
{
        
public function actionCreate()
{
    $model = new Lists();

    if ($model->load(Yii::$app->request->post())) {
        if ($model->validate()) {
            // Save the form value
            $model->save();
            // show message
             Yii::$app->getSession()->setFlash('success' , 'Guest List Has added successfully');
             //redirect
            return $this->redirect('/guestbook/web/index.php?r=lists');
            return;
        }
    }

    return $this->render('create', [
        'model' => $model,
    ]);
}

    public function actionDelete($id)
    {
                 $model = Lists::findOne($id);
                 $model->delete();

        // show message
             Yii::$app->getSession()->setFlash('success' , 'Guestlist Has deleted successfully');
             //redirect
            return $this->redirect('/guestbook/web/index.php?r=lists');    }
    
    public function actionDetails($id)
 
    {
        $list = Lists::find()
        ->where(['id'=>$id])
        ->one();

        //render the view 
        return $this->render('details', ['list'=>$list]);
    }
   public function actionEdit($id){
        $model = Lists::findOne($id);

if ($model->load(Yii::$app->request->post())) {
    if ($model->validate()) {
    // Save the form value
        $model->save();
        // show message
         Yii::$app->getSession()->setFlash('success' , 'Guestlist Has edited successfully');
         //redirect
        return $this->redirect('/guestbook/web/index.php?r=lists');
        return;
}
    }

    return $this->render('edit', [
        'model' => $model,
    ]);

       
    }
    
     public function actionIndex()
    {
        // Create Query
        $query = Lists::find();

        
          $pagination = new Pagination([
            'defaultPageSize' => 10,
            'totalCount' => $query->count(),
        ]);

        $list = $query->orderBy('created_date DESC')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('index', [
            'lists' => $list,
            'pagination' => $pagination,
        ]);

    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\data\Pagination;
use app\models\User;

class UserController extends Controller
{
    public function actionLogin()
    {
        return $this->render('login');
    }

   
public function actionRegister()
{
    $model = new User();

    if ($model->load(Yii::$app->request->post())) {
        if ($model->validate()) {
            // form inputs are valid, do something here
            $model->save();
            // show success message
            Yii::$app->getSession()->setFlash('success' , 'Your Registration was successful');
            return $this->redirect('/guestbook/web/index.php');
            
        }
    }
	
    return $this->render('register', [
        'model' => $model,
    ]);
}



}

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
$mlink = "/yiiframework/web/index.php?r=site/index";
 $chikhalifa ="<a href=" . $mlink . ">Chikhalifa</a>";
/* @var $this \yii\web\View */
/* @var $content string */
 
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
 
<?php $this->beginBody() ?>
    <div class="wrap">
        <?php
            NavBar::begin([
                'brandLabel' => 'Chika guestbook App',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
           echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-left'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'About', 'url' => ['/site/about']],
          ['label' => 'Guest List', 'url' => ['/lists/index']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
          
           

        ],
    ]);

     echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        
        'items' => [
            
            Yii::$app->user->isGuest ? (

                ['label' => 'Login', 'url' => ['/site/login']]

            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )

                . Html::endForm()
                . '</li>'
            )
		
        ],
	   
	   
    ]);
echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        
        'items' => [
                                        ['label' => 'Register', 'url' => ['user/register'], 'options' => ['class' => 'navbar-nav navbar-right']]

		
        ],
	   
	   
    ]);
    NavBar::end();
    ?>

 
        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?= $content ?>
        </div>
    </div>
 
    <footer class="footer">
        <div class="container">
            <p class="pull-left">&copy; Chika <?= date('Y') ?></p>
            <p class="pull-right"><?= $chikhalifa ?></p>
        </div>
    </footer>
 
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>